version: 0.2

phases:
  install:
    commands:
      - npm install
      - npm i -g serverless
  build:
    commands:
      - serverless deploy
  post_build:
    commands:
      - aws s3 sync ./dist s3://volodka-trello-api/