# NOTE: update this with your service name
service: ku

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  #environment:
  #  SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}

functions:
  createColumn:
    handler: controllers/columnC.pushColumn
    events:
      - http:
          path: pushColumn
          method: post
          cors: true
  getColumns:
    handler: controllers/columnC.getColumns
    events:
      - http:
          path: getColumns
          method: get
          cors: true
  getColumn:
    handler: controllers/columnC.getColumn
    events:
      - http:
          path: getColumn/{id}
          method: get
          cors: true
  deleteColumn:
    handler: controllers/columnC.deleteColumn
    vents:
      - http:
          path: deleteColumn/{id}
          method: delete
          cors: true
  updateColumn:
    handler: controllers/columnC.updateColumn
    events:
      - http:
          path: updateColumn/{id}
          method: put
          cors: true


  createCard:
    handler: controllers/cardC.pushCard
    events:
      - http:
          path: pushCard
          method: post
          cors: true
  getCards:
      handler: controllers/cardC.getCards
      events:
        - http:
            path: getCards
            method: get
            cors: true
  getCard:
      handler: controllers/cardC.getCard
      events:
        - http:
            path: getCard/{id}
            method: get
            cors: true
  deleteCard:
      handler: controllers/cardC.deleteCard
      vents:
        - http:
            path: deleteCard/{id}
            method: delete
            cors: true
  updateCard:
      handler: controllers/cardC.updateCard
      events:
        - http:
            path: updateCard/{id}
            method: put
            cors: true